apiVersion: v1
kind: Service
metadata:
  name: job-platform
  namespace: job-platform
  labels:
    app: job-platform
spec:
  type: ClusterIP
  selector:
    app: job-platform
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
